language: php

dist: trusty

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

sudo: true


addons:
  sonarcloud:
    organization: "amineherradi-github"
    token:
      secure: "f3c30b7178509b3fbb07d9e5bc716e0c244b8dd0"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

install:
  - travis_retry composer update

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../evaneos --ignore=*/vendor/*
  - sonar-scanner